// <auto-generated />
using Catalog.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201031173536_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Description = "Description for product {i}",
                            Name = "Product 1",
                            Price = 518m
                        },
                        new
                        {
                            ProductID = 2,
                            Description = "Description for product {i}",
                            Name = "Product 2",
                            Price = 517m
                        },
                        new
                        {
                            ProductID = 3,
                            Description = "Description for product {i}",
                            Name = "Product 3",
                            Price = 125m
                        },
                        new
                        {
                            ProductID = 4,
                            Description = "Description for product {i}",
                            Name = "Product 4",
                            Price = 826m
                        },
                        new
                        {
                            ProductID = 5,
                            Description = "Description for product {i}",
                            Name = "Product 5",
                            Price = 227m
                        },
                        new
                        {
                            ProductID = 6,
                            Description = "Description for product {i}",
                            Name = "Product 6",
                            Price = 484m
                        },
                        new
                        {
                            ProductID = 7,
                            Description = "Description for product {i}",
                            Name = "Product 7",
                            Price = 363m
                        },
                        new
                        {
                            ProductID = 8,
                            Description = "Description for product {i}",
                            Name = "Product 8",
                            Price = 496m
                        },
                        new
                        {
                            ProductID = 9,
                            Description = "Description for product {i}",
                            Name = "Product 9",
                            Price = 260m
                        },
                        new
                        {
                            ProductID = 10,
                            Description = "Description for product {i}",
                            Name = "Product 10",
                            Price = 578m
                        },
                        new
                        {
                            ProductID = 11,
                            Description = "Description for product {i}",
                            Name = "Product 11",
                            Price = 117m
                        },
                        new
                        {
                            ProductID = 12,
                            Description = "Description for product {i}",
                            Name = "Product 12",
                            Price = 363m
                        },
                        new
                        {
                            ProductID = 13,
                            Description = "Description for product {i}",
                            Name = "Product 13",
                            Price = 591m
                        },
                        new
                        {
                            ProductID = 14,
                            Description = "Description for product {i}",
                            Name = "Product 14",
                            Price = 115m
                        },
                        new
                        {
                            ProductID = 15,
                            Description = "Description for product {i}",
                            Name = "Product 15",
                            Price = 536m
                        },
                        new
                        {
                            ProductID = 16,
                            Description = "Description for product {i}",
                            Name = "Product 16",
                            Price = 534m
                        },
                        new
                        {
                            ProductID = 17,
                            Description = "Description for product {i}",
                            Name = "Product 17",
                            Price = 939m
                        },
                        new
                        {
                            ProductID = 18,
                            Description = "Description for product {i}",
                            Name = "Product 18",
                            Price = 707m
                        },
                        new
                        {
                            ProductID = 19,
                            Description = "Description for product {i}",
                            Name = "Product 19",
                            Price = 141m
                        },
                        new
                        {
                            ProductID = 20,
                            Description = "Description for product {i}",
                            Name = "Product 20",
                            Price = 273m
                        },
                        new
                        {
                            ProductID = 21,
                            Description = "Description for product {i}",
                            Name = "Product 21",
                            Price = 626m
                        },
                        new
                        {
                            ProductID = 22,
                            Description = "Description for product {i}",
                            Name = "Product 22",
                            Price = 999m
                        },
                        new
                        {
                            ProductID = 23,
                            Description = "Description for product {i}",
                            Name = "Product 23",
                            Price = 671m
                        },
                        new
                        {
                            ProductID = 24,
                            Description = "Description for product {i}",
                            Name = "Product 24",
                            Price = 921m
                        },
                        new
                        {
                            ProductID = 25,
                            Description = "Description for product {i}",
                            Name = "Product 25",
                            Price = 568m
                        },
                        new
                        {
                            ProductID = 26,
                            Description = "Description for product {i}",
                            Name = "Product 26",
                            Price = 369m
                        },
                        new
                        {
                            ProductID = 27,
                            Description = "Description for product {i}",
                            Name = "Product 27",
                            Price = 521m
                        },
                        new
                        {
                            ProductID = 28,
                            Description = "Description for product {i}",
                            Name = "Product 28",
                            Price = 609m
                        },
                        new
                        {
                            ProductID = 29,
                            Description = "Description for product {i}",
                            Name = "Product 29",
                            Price = 325m
                        },
                        new
                        {
                            ProductID = 30,
                            Description = "Description for product {i}",
                            Name = "Product 30",
                            Price = 278m
                        },
                        new
                        {
                            ProductID = 31,
                            Description = "Description for product {i}",
                            Name = "Product 31",
                            Price = 716m
                        },
                        new
                        {
                            ProductID = 32,
                            Description = "Description for product {i}",
                            Name = "Product 32",
                            Price = 295m
                        },
                        new
                        {
                            ProductID = 33,
                            Description = "Description for product {i}",
                            Name = "Product 33",
                            Price = 496m
                        },
                        new
                        {
                            ProductID = 34,
                            Description = "Description for product {i}",
                            Name = "Product 34",
                            Price = 588m
                        },
                        new
                        {
                            ProductID = 35,
                            Description = "Description for product {i}",
                            Name = "Product 35",
                            Price = 310m
                        },
                        new
                        {
                            ProductID = 36,
                            Description = "Description for product {i}",
                            Name = "Product 36",
                            Price = 516m
                        },
                        new
                        {
                            ProductID = 37,
                            Description = "Description for product {i}",
                            Name = "Product 37",
                            Price = 595m
                        },
                        new
                        {
                            ProductID = 38,
                            Description = "Description for product {i}",
                            Name = "Product 38",
                            Price = 110m
                        },
                        new
                        {
                            ProductID = 39,
                            Description = "Description for product {i}",
                            Name = "Product 39",
                            Price = 745m
                        },
                        new
                        {
                            ProductID = 40,
                            Description = "Description for product {i}",
                            Name = "Product 40",
                            Price = 101m
                        },
                        new
                        {
                            ProductID = 41,
                            Description = "Description for product {i}",
                            Name = "Product 41",
                            Price = 683m
                        },
                        new
                        {
                            ProductID = 42,
                            Description = "Description for product {i}",
                            Name = "Product 42",
                            Price = 249m
                        },
                        new
                        {
                            ProductID = 43,
                            Description = "Description for product {i}",
                            Name = "Product 43",
                            Price = 109m
                        },
                        new
                        {
                            ProductID = 44,
                            Description = "Description for product {i}",
                            Name = "Product 44",
                            Price = 153m
                        },
                        new
                        {
                            ProductID = 45,
                            Description = "Description for product {i}",
                            Name = "Product 45",
                            Price = 670m
                        },
                        new
                        {
                            ProductID = 46,
                            Description = "Description for product {i}",
                            Name = "Product 46",
                            Price = 947m
                        },
                        new
                        {
                            ProductID = 47,
                            Description = "Description for product {i}",
                            Name = "Product 47",
                            Price = 883m
                        },
                        new
                        {
                            ProductID = 48,
                            Description = "Description for product {i}",
                            Name = "Product 48",
                            Price = 397m
                        },
                        new
                        {
                            ProductID = 49,
                            Description = "Description for product {i}",
                            Name = "Product 49",
                            Price = 213m
                        },
                        new
                        {
                            ProductID = 50,
                            Description = "Description for product {i}",
                            Name = "Product 50",
                            Price = 590m
                        },
                        new
                        {
                            ProductID = 51,
                            Description = "Description for product {i}",
                            Name = "Product 51",
                            Price = 705m
                        },
                        new
                        {
                            ProductID = 52,
                            Description = "Description for product {i}",
                            Name = "Product 52",
                            Price = 389m
                        },
                        new
                        {
                            ProductID = 53,
                            Description = "Description for product {i}",
                            Name = "Product 53",
                            Price = 265m
                        },
                        new
                        {
                            ProductID = 54,
                            Description = "Description for product {i}",
                            Name = "Product 54",
                            Price = 972m
                        },
                        new
                        {
                            ProductID = 55,
                            Description = "Description for product {i}",
                            Name = "Product 55",
                            Price = 603m
                        },
                        new
                        {
                            ProductID = 56,
                            Description = "Description for product {i}",
                            Name = "Product 56",
                            Price = 519m
                        },
                        new
                        {
                            ProductID = 57,
                            Description = "Description for product {i}",
                            Name = "Product 57",
                            Price = 846m
                        },
                        new
                        {
                            ProductID = 58,
                            Description = "Description for product {i}",
                            Name = "Product 58",
                            Price = 203m
                        },
                        new
                        {
                            ProductID = 59,
                            Description = "Description for product {i}",
                            Name = "Product 59",
                            Price = 357m
                        },
                        new
                        {
                            ProductID = 60,
                            Description = "Description for product {i}",
                            Name = "Product 60",
                            Price = 857m
                        },
                        new
                        {
                            ProductID = 61,
                            Description = "Description for product {i}",
                            Name = "Product 61",
                            Price = 962m
                        },
                        new
                        {
                            ProductID = 62,
                            Description = "Description for product {i}",
                            Name = "Product 62",
                            Price = 753m
                        },
                        new
                        {
                            ProductID = 63,
                            Description = "Description for product {i}",
                            Name = "Product 63",
                            Price = 270m
                        },
                        new
                        {
                            ProductID = 64,
                            Description = "Description for product {i}",
                            Name = "Product 64",
                            Price = 981m
                        },
                        new
                        {
                            ProductID = 65,
                            Description = "Description for product {i}",
                            Name = "Product 65",
                            Price = 862m
                        },
                        new
                        {
                            ProductID = 66,
                            Description = "Description for product {i}",
                            Name = "Product 66",
                            Price = 821m
                        },
                        new
                        {
                            ProductID = 67,
                            Description = "Description for product {i}",
                            Name = "Product 67",
                            Price = 867m
                        },
                        new
                        {
                            ProductID = 68,
                            Description = "Description for product {i}",
                            Name = "Product 68",
                            Price = 103m
                        },
                        new
                        {
                            ProductID = 69,
                            Description = "Description for product {i}",
                            Name = "Product 69",
                            Price = 805m
                        },
                        new
                        {
                            ProductID = 70,
                            Description = "Description for product {i}",
                            Name = "Product 70",
                            Price = 119m
                        },
                        new
                        {
                            ProductID = 71,
                            Description = "Description for product {i}",
                            Name = "Product 71",
                            Price = 938m
                        },
                        new
                        {
                            ProductID = 72,
                            Description = "Description for product {i}",
                            Name = "Product 72",
                            Price = 928m
                        },
                        new
                        {
                            ProductID = 73,
                            Description = "Description for product {i}",
                            Name = "Product 73",
                            Price = 962m
                        },
                        new
                        {
                            ProductID = 74,
                            Description = "Description for product {i}",
                            Name = "Product 74",
                            Price = 139m
                        },
                        new
                        {
                            ProductID = 75,
                            Description = "Description for product {i}",
                            Name = "Product 75",
                            Price = 589m
                        },
                        new
                        {
                            ProductID = 76,
                            Description = "Description for product {i}",
                            Name = "Product 76",
                            Price = 477m
                        },
                        new
                        {
                            ProductID = 77,
                            Description = "Description for product {i}",
                            Name = "Product 77",
                            Price = 990m
                        },
                        new
                        {
                            ProductID = 78,
                            Description = "Description for product {i}",
                            Name = "Product 78",
                            Price = 618m
                        },
                        new
                        {
                            ProductID = 79,
                            Description = "Description for product {i}",
                            Name = "Product 79",
                            Price = 351m
                        },
                        new
                        {
                            ProductID = 80,
                            Description = "Description for product {i}",
                            Name = "Product 80",
                            Price = 620m
                        },
                        new
                        {
                            ProductID = 81,
                            Description = "Description for product {i}",
                            Name = "Product 81",
                            Price = 485m
                        },
                        new
                        {
                            ProductID = 82,
                            Description = "Description for product {i}",
                            Name = "Product 82",
                            Price = 223m
                        },
                        new
                        {
                            ProductID = 83,
                            Description = "Description for product {i}",
                            Name = "Product 83",
                            Price = 496m
                        },
                        new
                        {
                            ProductID = 84,
                            Description = "Description for product {i}",
                            Name = "Product 84",
                            Price = 735m
                        },
                        new
                        {
                            ProductID = 85,
                            Description = "Description for product {i}",
                            Name = "Product 85",
                            Price = 573m
                        },
                        new
                        {
                            ProductID = 86,
                            Description = "Description for product {i}",
                            Name = "Product 86",
                            Price = 426m
                        },
                        new
                        {
                            ProductID = 87,
                            Description = "Description for product {i}",
                            Name = "Product 87",
                            Price = 130m
                        },
                        new
                        {
                            ProductID = 88,
                            Description = "Description for product {i}",
                            Name = "Product 88",
                            Price = 523m
                        },
                        new
                        {
                            ProductID = 89,
                            Description = "Description for product {i}",
                            Name = "Product 89",
                            Price = 984m
                        },
                        new
                        {
                            ProductID = 90,
                            Description = "Description for product {i}",
                            Name = "Product 90",
                            Price = 790m
                        },
                        new
                        {
                            ProductID = 91,
                            Description = "Description for product {i}",
                            Name = "Product 91",
                            Price = 670m
                        },
                        new
                        {
                            ProductID = 92,
                            Description = "Description for product {i}",
                            Name = "Product 92",
                            Price = 492m
                        },
                        new
                        {
                            ProductID = 93,
                            Description = "Description for product {i}",
                            Name = "Product 93",
                            Price = 752m
                        },
                        new
                        {
                            ProductID = 94,
                            Description = "Description for product {i}",
                            Name = "Product 94",
                            Price = 887m
                        },
                        new
                        {
                            ProductID = 95,
                            Description = "Description for product {i}",
                            Name = "Product 95",
                            Price = 139m
                        },
                        new
                        {
                            ProductID = 96,
                            Description = "Description for product {i}",
                            Name = "Product 96",
                            Price = 929m
                        },
                        new
                        {
                            ProductID = 97,
                            Description = "Description for product {i}",
                            Name = "Product 97",
                            Price = 978m
                        },
                        new
                        {
                            ProductID = 98,
                            Description = "Description for product {i}",
                            Name = "Product 98",
                            Price = 127m
                        },
                        new
                        {
                            ProductID = 99,
                            Description = "Description for product {i}",
                            Name = "Product 99",
                            Price = 290m
                        },
                        new
                        {
                            ProductID = 100,
                            Description = "Description for product {i}",
                            Name = "Product 100",
                            Price = 849m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 464
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 375
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 983
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 934
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 101
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 852
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 851
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 464
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 284
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 174
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 514
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 723
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 739
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 604
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 877
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 164
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 807
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 410
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 782
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 353
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 937
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 860
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 214
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 658
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 800
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 471
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 868
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 141
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 333
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 992
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 166
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 326
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 893
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 613
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 623
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 187
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 375
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 427
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 366
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 896
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 386
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 727
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 775
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 793
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 727
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 325
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 165
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 466
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 303
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 763
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 297
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 173
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 236
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 702
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 317
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 604
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 260
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 424
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 234
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 630
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 983
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 809
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 230
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 292
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 107
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 287
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 830
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 225
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 981
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 789
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 788
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 480
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 143
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 885
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 967
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 310
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 184
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 421
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 931
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 574
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 405
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 502
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 838
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 570
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 794
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 993
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 190
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 290
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 396
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 118
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 927
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 950
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 292
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 736
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 912
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 576
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 596
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 583
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 785
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 539
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
